openapi: 3.0.0
info:
  title: Spec
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /rankings:
    get:
      summary: Ranking一覧を取得する
      tags: []
      operationId: get-rankings
      responses:
        '200':
          $ref: '#/components/responses/Rankings'
    post:
      summary: Rankingを作成する
      operationId: post-rankings
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ranking:
                  type: object
                  required:
                    - title
                    - genre
                  properties:
                    title:
                      type: string
                    genre:
                      type: string
              required:
                - ranking
      responses:
        '201':
          $ref: '#/components/responses/Ranking'
  '/rankings/{:id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Rankingを取得する
      tags: []
      operationId: get-ranking
      responses:
        '200':
          $ref: '#/components/responses/Ranking'
      description: ''
  '/accounts/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Accountを取得する
      responses:
        '200':
          $ref: '#/components/responses/Account'
      operationId: get-accounts-id
  /sign_in:
    post:
      summary: サインインする
      operationId: post-sign_in
      responses:
        '200':
          $ref: '#/components/responses/AccountWithToken'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: object
                  required:
                    - username
                    - password
                  properties:
                    username:
                      type: string
                    password:
                      type: string
              required:
                - account
        description: ''
  /sign_up:
    post:
      summary: サインアップする
      operationId: post-sign_up
      responses:
        '201':
          $ref: '#/components/responses/AccountWithToken'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: object
                  required:
                    - username
                    - password
                  properties:
                    username:
                      type: string
                    password:
                      type: string
              required:
                - account
components:
  schemas: {}
  responses:
    Ranking:
      description: ''
      content:
        application/json:
          schema:
            $ref: ../response/RankingRes.yaml
    Rankings:
      description: ''
      content:
        application/json:
          schema:
            $ref: ../response/RankingsRes.yaml
    Account:
      description: ''
      content:
        application/json:
          schema:
            $ref: ../response/AccountRes.yaml
    AccountWithToken:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              account:
                $ref: ../response/AccountRes.yaml
              token:
                type: string
            required:
              - account
              - token
