default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: best-10_development

test:
  <<: *default
  database: best-10_test

production:
  <<: *default
  # 一旦herokuにデプロイ
  database: d8hg36rp7arl80
  host: ec2-54-173-77-184.compute-1.amazonaws.com
  username: ocreouuxviqwbo
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
