common: &default_settings
  license_key: ENV.fetch("NEW_RELIC_LICENSE_KEY")
  app_name: best-10

  distributed_tracing:
    enabled: true
  log_level: info

  application_logging:
    enabled: true
    forwarding:
      enabled: true
      max_samples_stored: 10000
    metrics:
      enabled: true
    local_decorating:
      enabled: false

development:
  <<: *default_settings
  app_name: best-10 (Development)

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: best-10 (Staging)

production:
  <<: *default_settings
