name: Release

on:
  push:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: add nullable
        shell: bash
        run: |
          for file in openapi/schema/*; do
            sed -i -e "s/- 'null'/- 'null'\n    nullable: true/g" $file
            sed -i -e "s/type: 'null'/nullable: true/g" $file
          done
          for file in openapi/response/*; do
            sed -i -e "s/- 'null'/- 'null'\n    nullable: true/g" $file
            sed -i -e "s/type: 'null'/nullable: true/g" $file
          done
#          for file in openapi/schema/*; do
#            sed -i -e "s/- 'null'/nullable: true/g" $file
#            sed -i -e "s/  nullable: true/nullable: true/g" $file
#            sed -i -e "N;s/type:\n *- string/type: string/g" $file
#            sed -i -e "N;s/type:\n *- number/type: number/g" $file
#            sed -i -e "N;s/type:\n *- integer/type: integer/g" $file
#          done
      - name: Build project
        run: |
          npm ci && npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build