name: Release

on:
  push:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: transform nullable
        run: |
          for file in openapi/schema/*; do \
            sed -i -e "s/- 'null'/- 'null'\n      nullable: true/g" $file \
          done
      - name: Build project
        run: |
          npm ci && npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build